#ifndef TA_CONTEXT_BASED_AUTHENTICATION_H
#define TA_CONTEXT_BASED_AUTHENTICATION_H


#define TA_CONTEXT_BASED_AUTHENTICATION_UUID \
    { 0xcf06c1aa, 0xd7e5, 0x48c5, \
                    { 0x87, 0x81, 0xb4, 0x71, 0x8f, 0xaf, 0xf7, 0xa3} }


#define TA_CONTEXT_BASED_AUTHENTICATION_CMD_GET_NONCE       0
#define TA_CONTEXT_BASED_AUTHENTICATION_CMD_ENROLL          1
#define TA_CONTEXT_BASED_AUTHENTICATION_CMD_PROVE           2
#define TA_CONTEXT_BASED_AUTHENTICATION_CMD_VERIFY          3


#endif /* TA_CONTEXT_BASED_AUTHENTICATION_H */
